BooksWebPortal/Models/BookModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BooksWebPortal.Models
{
    public class BookModel
    {
        public string Author { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
        public DateTime Publish_date { get; set; }
        public string Description { get; set; }
    }
}

BooksWebPortal/Controllers/BookController.cs
using BooksWebPortal.ExternalBookService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BooksWebPortal.Controllers
{
    public class BookController : Controller
    {
        //
        // GET: /Book/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SearchBooks(string searchString, int searchAttribute)
        {
            if (searchString != String.Empty)
            {
                var bookService = new BookService();
                ViewData.Model = bookService.Search(searchString, searchAttribute);
            }
            return View("Index");
        }
    }
}

BooksWebPortal/Views/Book/Index.cshtml
@model IEnumerable<BooksWebPortal.Models.BookModel>
@{
    ViewBag.Title = "Index";
}
<script type="text/javascript">
    function validate() {
        if ($("#searchString").val() == "") {
            $("#searchString").stop().css("background-color", "#FF7777").animate({ backgroundColor: "#FFFFFF" }, 1500);
        }
    }
</script>
<head>
    <title>Booksearch</title>
    <link href="@Url.Content("~/Content/Site.css")" type="text/css" rel="stylesheet"/>
</head>

<body>
    <header>
        <h1 class="headline1">Book search</h1>
    </header>
    
        @using (Html.BeginForm("SearchBooks", "Book", FormMethod.Post, new { onsubmit = "validate()" }))
        {
            <div class="searchSettings">
                <ul>
                    <li><h3>Search by: </h3></li>
                    <li><label><input id="title" type="radio" name="searchAttribute" value=1 checked />Title</label></li>
                    <li><label><input id="titleAndDescription" type="radio" name="searchAttribute" value=3 />Title and Description</label></li>
                    <li><label><input id="author" type="radio" name="searchAttribute" value=2 />Author</label></li>
                    <li><input class="textbox" id="searchString" type="text" name="searchString" /></li>
                    <li><button class="button" title="Search" type="submit">Search</button></li>
                </ul>
            </div>
        }

    <div class="results">
        @if (Model != null)
        {
            if (Model.Count() == 0)
            {
                    <p>No matching books were found</p>
            }
            else
            {
                foreach (var m in Model)
                {   
                    <hr>
                    <p class="text"><b>Title:</b>       @m.Title</p>
                    <p class="text"><b>Author</b>       @m.Author</p> 
                    <p class="text"><b>Price:</b>       @m.Price $</p>
                    <p class="text"><b>Description</b>  @m.Description</p>

                }
            }
        }
    </div>
</body>

BooksWebPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>